tabby/bot/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('betting', views.betting, name='betting'),
    path('sim', views.sim, name='sim'),
]

tabby/tab/urls.py
from django.urls import path

from .views import MeetingListView, MeetingDetailView, RaceDetailView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('meetings/', MeetingListView.as_view(), name='meetings'),
    path('meetings/<int:pk>', MeetingDetailView.as_view(), name='meeting'),
    path('races/<int:pk>', RaceDetailView.as_view(), name='race'),
]

tabby/tabby/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    # path('', include('bot.urls')),
    # path('betfair/', include('betfair.urls')),
    path('', include('tab.urls')),
    path('admin/', admin.site.urls),
]

tabby/tab/models.py
import logging

from django.db import models

from betfair.models import Market, RunnerBook, Runner as BfRunner
from .managers import RaceManager, FixedOddManager, RunnerManager, VarManager

logger = logging.getLogger(__name__)


class Meeting(models.Model):
    LOCATIONS = (
        ('QLD', 'Queensland'),
    )
    TYPES = (
        ('G', 'Grayhound'),
        ('R', 'Racing'),
        ('H', 'Harness'),
    )

    name = models.CharField(max_length=50)
    date = models.DateField()

    location = models.CharField(max_length=10, choices=LOCATIONS)
    race_type = models.CharField(max_length=1, choices=TYPES)
    rail_position = models.CharField(max_length=30, null=True)
    track_condition = models.CharField(max_length=30, null=True)
    venue_mnemonic = models.CharField(max_length=10)
    weather_condition = models.CharField(max_length=30, null=True)

    def races_finished(self):
        return Race.objects.handled(self, True, True).all()

    def races_unprocessed(self):
        return Race.objects.handled(self, True).all()

    def races_upcoming(self):
        return Race.objects.handled(self).all()


class Race(models.Model):
    objects = RaceManager()

    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)

    number = models.IntegerField()

    link_self = models.CharField(max_length=255)
    link_form = models.CharField(max_length=255, null=True)
    link_big_bets = models.CharField(max_length=255)
    distance = models.IntegerField()
    name = models.CharField(max_length=50)
    start_time = models.DateTimeField()

    direction = models.CharField(max_length=20, null=True)
    has_fixed_odds = models.BooleanField(default=True)
    has_parimutuel = models.BooleanField(default=True)
    class_conditions = models.CharField(max_length=20, null=True)
    status = models.CharField(max_length=20, null=True)
    number_of_places = models.IntegerField(null=True)

    has_results = models.BooleanField(default=False)
    has_processed = models.BooleanField(default=False)

    class Meta:
        ordering = ['start_time']

    def __str__(self):
        return f'<Race [{self.id}] {self.meeting.name} R{self.number} time={self.start_time}>'

    @property
    def win_market(self):
        try:
            return self.market_set.filter(
                market_type='WIN'
            ).get()
        except:
            return None


class Runner(models.Model):
    objects = RunnerManager()

    race = models.ForeignKey(Race, on_delete=models.CASCADE)

    link_form = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=50)
    trainer_name = models.CharField(max_length=100, null=True)
    rider_name = models.CharField(max_length=100, null=True)
    runner_number = models.IntegerField()
    barrier_number = models.IntegerField()
    handicap_weight = models.FloatField(null=True)
    harness_handicap = models.FloatField(null=True)
    last_5_starts = models.CharField(max_length=5, null=True)
    dfs_form_rating = models.IntegerField(null=True)
    tech_form_rating = models.IntegerField(null=True)
    fixed_betting_status = models.CharField(max_length=20, null=True)
    parimutuel_betting_status = models.CharField(max_length=20, null=True)

    class Meta:
        ordering = ['barrier_number', 'runner_number']

    def __str__(self):
        return f'Runner(num={self.runner_number} name={self.name})'

    def fo(self):
        return self.fixedodd_set.all()[:5]

    def odds_change(self):
        first = self.fixedodd_set.first()
        last = list(self.fixedodd_set.all()[:5])[-1]
        first_perc = 1 / first.win_dec
        last_perc = 1 / last.win_dec
        return (first_perc - last_perc) / last_perc

    @property
    def rbook(self):
        if not hasattr(self, '_rbook'):
            self._rbook = None
            market = self.race.market_set.first()
            if market:
                book = market.book_set.last()
                try:
                    self._rbook = RunnerBook.objects.get(
                        book=book,
                        runner__cloth_number=self.runner_number
                    )
                except:
                    self._rbook = None
        return self._rbook

    @property
    def back(self):
        """Current betfair best available back odds"""
        if self.rbook:
            return self.rbook.lay_price

    @property
    def lay(self):
        """Current betfair best available back odds"""
        if self.rbook:
            return self.rbook.back_price

    @property
    def trade(self):
        """Current betfair best available back odds"""
        if self.rbook:
            if not self.rbook.last_price_traded:
                return None
            return self.rbook.last_price_traded


class FixedOdd(models.Model):
    objects = FixedOddManager()

    runner = models.ForeignKey(Runner, on_delete=models.CASCADE)
    as_at = models.DateTimeField()
    win_dec = models.FloatField()
    place_dec = models.FloatField()

    class Meta:
        ordering = ['-as_at']

    @property
    def win_perc(self):
        return 1 / self.win_dec if self.win_dec else 0

    @property
    def place_perc(self):
        return 1 / self.place_dec if self.place_dec else 0

    @property
    def win_back(self):
        """Marked up with 30% to place a bet"""
        win_est = self.win_est
        if not win_est:
            return 0
        win_est *= 0.90
        return 1 / win_est

    @property
    def win_lay(self):
        """Marked up with 30% to place a bet"""
        win_est = self.win_est
        if not win_est:
            return 0
        win_est *= 1.10
        return 1 / win_est


class ParimutuelOdd(models.Model):
    runner = models.ForeignKey(Runner, on_delete=models.CASCADE)
    as_at = models.DateTimeField()
    win_dec = models.FloatField()
    place_dec = models.FloatField(null=True)

    class Meta:
        ordering = ['-as_at']


class Result(models.Model):
    race = models.ForeignKey(Race, on_delete=models.CASCADE)
    runner = models.OneToOneField(Runner, on_delete=models.CASCADE)
    pos = models.IntegerField()

    class Meta:
        ordering = ['pos']

    @property
    def won(self):
        return self.pos == 1

    @property
    def placed(self):
        return self.pos <= self.race.number_of_places


class RunnerMeta(models.Model):
    race = models.ForeignKey(Race, on_delete=models.CASCADE)
    runner = models.OneToOneField(Runner, on_delete=models.CASCADE)

    win_odds = models.FloatField()
    place_odds = models.FloatField()
    rating = models.FloatField()

    won = models.BooleanField()
    placed = models.BooleanField()

    def __str__(self):
        return f'RunnerMeta(race={self.race} runner={self.runner})'


class Var(models.Model):
    objects = VarManager()

    key = models.CharField(max_length=20)
    val1 = models.FloatField(default=0, blank=True)
    val2 = models.FloatField(default=0, blank=True)
    val3 = models.FloatField(null=True, blank=True)
    val4 = models.FloatField(null=True, blank=True)
    val5 = models.FloatField(null=True, blank=True)
    ran_at = models.DateTimeField()

    def __str__(self):
        return f'Var(key={self.key})'

tabby/tab/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Meeting, Race


def index(request):
    return render(request, 'tab/index.html', {})


class MeetingListView(ListView):
    model = Meeting
    queryset = Meeting.objects.order_by('-date')

    # def head(self, *args, **kwargs):
    #     last_book = self.get_queryset().latest('publication_date')
    #     response = HttpResponse('')
    #     # RFC 1123 date format
    #     response['Last-Modified'] = last_book.publication_date.strftime('%a, %d %b %Y %H:%M:%S GMT')
    #     return response


class MeetingDetailView(DetailView):
    model = Meeting


class RaceDetailView(DetailView):
    model = Race

tabby/tab/templates/tab/index.html
{% extends 'base.html' %}

{% block content %}
<ul>
    <li><a href="{% url 'meetings' %}">Meetings</a></li>
</ul>
{% endblock %}

tabby/tab/templates/tab/meeting_detail.html
{% extends 'base.html' %}

{% block content %}
    <p><small><a href="{% url 'meetings' %}">Back to meetings</a></small></p>
    <h3>{{ object.name }}</h3>
    <p>Date: {{ object.date }}</p>
    <table border="1" cellpadding="5">
    <thead>
        <tr>
            <th>No</th>
            <th>Start time</th>
            <th>Distance</th>
            <th>Name</th>
            <th>Status</th>
            <th>Class Conditions</th>
            <th>Direction</th>
            <th>Places</th>
            <th>Results and processed?</th>
        </tr>
    </thead>
    <tbody>
        {% for race in object.race_set.all %}
            <tr>
                <td><a href="{% url 'race' pk=race.pk %}">{{ race.number }}</a></td>
                <td>{{ race.start_time|time:"G:i" }}</td>
                <td>{{ race.distance }}</td>
                <td>{{ race.name }}</td>
                <td>{{ race.status }}</td>
                <td>{{ race.class_conditions }}</td>
                <td>{{ race.direction }}</td>
                <td>{{ race.number_of_places }}</td>
                <td>{{ race.has_results }} & {{ race.has_processed }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

tabby/tab/templates/tab/meeting_list.html
{% extends 'base.html' %}

{% block content %}
    <h3>Meetings</h3>
    <table border="1" cellpadding="5">
        <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Type</th>
            <th>Venue</th>
            <th>Track</th>
            <th>Weather</th>
            <th>Finished</th>
            <th>Unprocessed</th>
            <th>Upcoming</th>
        </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'meeting' pk=object.pk %}">{{ object.name }}</a></td>
                    <td>{{ object.date }}</td>
                    <td>{{ object.race_type }}</td>
                    <td>{{ object.venue_mnemonic }}</td>
                    <td>{{ object.track_condition }}</td>
                    <td>{{ object.weather_condition }}</td>
                    <td>{% for race in object.races_finished %}
                        {{ race.number }}
                    {% endfor %}</td>
                    <td>{% for race in object.races_unprocessed %}
                        {{ race.number }}
                    {% endfor %}</td>
                    <td>{% for race in object.races_upcoming %}
                        {{ race.number }}
                    {% endfor %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

tabby/tab/templates/tab/race_detail.html
{% extends 'base.html' %}

{% block content %}
    <p><small><a href="{% url 'meeting' pk=object.meeting.pk %}">Back to {{ object.meeting.name }}</a></small></p>
    <h3>{{ object.number }} &mdash; <small>{{ object.name }}</small></h3>
    <h4>Time: {{ object.start_time|time:"G:i" }}</h4>

    <table border="1" cellpadding="5">
    <thead>
        <tr>
            <th>Results</th>
            <th>Barrier no</th>
            <th>Runner</th>
            <th>Last 5 starts</th>
            <th>DFS form</th>
            <th>Tech form</th>
            <th>Fixed betting</th>
            <th>Tote betting</th>
        </tr>
    </thead>
    <tbody>
        {% for runner in object.runner_set.all %}
            <tr>
                <td>{{ runner.result.pos }}</td>
                <td>{{ runner.barrier_number }}</td>
                <td>{{ runner.runner_number }} &mdash; {{ runner.name }}</td>
                <td>{{ runner.last_5_starts }}</td>
                <td>{{ runner.dfs_form_rating }}</td>
                <td>{{ runner.tech_form_rating }}</td>
                <td>{{ runner.fixed_betting_status }}</td>
                <td>{{ runner.parimutuel_betting_status }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}